import {
    ArrowUpRight,
    BadgeIndianRupee,
    Crown,
    Package,
    TrendingUp,
    Wallet,
} from "lucide-react";

const cards = [
    {
        title: "Total Revenue",
        value: "₹8.4L",
        growth: "+18%",
        icon: BadgeIndianRupee,
    },
    {
        title: "Packages Sold",
        value: "482",
        growth: "+12%",
        icon: Package,
    },
    {
        title: "Renewals",
        value: "348",
        growth: "+8%",
        icon: TrendingUp,
    },
    {
        title: "Top Package",
        value: "Gold",
        growth: "+15%",
        icon: Crown,
    },
];

export default function PackageSales() {
    return (
        <div className="space-y-6">
            {/* HERO */}

            <div className="rounded-3xl bg-gradient-to-r from-emerald-600 via-green-600 to-teal-600 p-8 text-white shadow-xl">
                <div>
                    <div className="mb-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-white/20">
                        <Wallet size={30} />
                    </div>

                    <h1 className="text-4xl font-bold">Package Sales</h1>

                    <p className="mt-3 max-w-2xl text-green-100">
                        Analyze package performance, renewals, upgrades, downgrades, profitability,
                        and revenue contribution.
                    </p>
                </div>
            </div>

            {/* FILTERS */}

            <div className="rounded-3xl border border-gray-200 bg-white p-6">
                <div className="grid grid-cols-12 gap-4">
                    <input
                        placeholder="Search package"
                        className="col-span-12 rounded-2xl border p-3 lg:col-span-4"
                    />

                    <input
                        type="date"
                        className="col-span-12 rounded-2xl border p-3 lg:col-span-3"
                    />

                    <select className="col-span-12 rounded-2xl border p-3 lg:col-span-2">
                        <option>All Packages</option>
                        <option>Gold</option>
                        <option>Silver</option>
                        <option>Premium</option>
                    </select>

                    <button className="col-span-12 rounded-2xl bg-green-600 p-3 font-semibold text-white lg:col-span-3">
                        Export Report
                    </button>
                </div>
            </div>

            {/* KPI CARDS */}

            <div className="grid grid-cols-12 gap-6">
                {cards.map((card, index) => {
                    const Icon = card.icon;

                    return (
                        <div key={index} className="col-span-12 md:col-span-6 xl:col-span-3">
                            <div className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
                                <div className="flex items-center justify-between">
                                    <div>
                                        <p className="text-sm text-gray-500">{card.title}</p>

                                        <h2 className="mt-3 text-4xl font-bold">{card.value}</h2>

                                        <div className="mt-3 flex items-center gap-2">
                                            <ArrowUpRight size={16} className="text-green-600" />

                                            <span className="font-medium text-green-600">
                                                {card.growth}
                                            </span>
                                        </div>
                                    </div>

                                    <div className="rounded-2xl bg-green-50 p-4">
                                        <Icon size={28} />
                                    </div>
                                </div>
                            </div>
                        </div>
                    );
                })}
            </div>
            {/* =====================================================
            ================= PACKAGE REVENUE =====================
            ===================================================== */}

            <div className="grid grid-cols-12 gap-6">
                <div className="col-span-12 xl:col-span-8">
                    <div className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
                        <div className="mb-8">
                            <h2 className="text-2xl font-bold">Package Revenue Analysis</h2>

                            <p className="mt-2 text-sm text-gray-500">
                                Revenue generated by different package categories.
                            </p>
                        </div>

                        <div className="grid grid-cols-2 gap-5 lg:grid-cols-4">
                            <div className="rounded-2xl bg-gray-50 p-5">
                                <p className="text-sm text-gray-500">Gold</p>

                                <h3 className="mt-3 text-3xl font-bold">₹3.2L</h3>
                            </div>

                            <div className="rounded-2xl bg-gray-50 p-5">
                                <p className="text-sm text-gray-500">Silver</p>

                                <h3 className="mt-3 text-3xl font-bold">₹2.4L</h3>
                            </div>

                            <div className="rounded-2xl bg-gray-50 p-5">
                                <p className="text-sm text-gray-500">Premium</p>

                                <h3 className="mt-3 text-3xl font-bold">₹1.8L</h3>
                            </div>

                            <div className="rounded-2xl bg-gray-50 p-5">
                                <p className="text-sm text-gray-500">Personal Training</p>

                                <h3 className="mt-3 text-3xl font-bold">₹1L</h3>
                            </div>
                        </div>
                    </div>
                </div>

                {/* PACKAGE COMPARISON */}

                <div className="col-span-12 xl:col-span-4">
                    <div className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
                        <h2 className="mb-8 text-2xl font-bold">Package Comparison</h2>

                        <div className="space-y-5">
                            {[
                                {
                                    name: "Gold",
                                    value: "82%",
                                },
                                {
                                    name: "Silver",
                                    value: "68%",
                                },
                                {
                                    name: "Premium",
                                    value: "54%",
                                },
                                {
                                    name: "PT",
                                    value: "35%",
                                },
                            ].map((item, index) => (
                                <div key={index}>
                                    <div className="mb-3 flex justify-between">
                                        <span>{item.name}</span>

                                        <span>{item.value}</span>
                                    </div>

                                    <div className="h-3 rounded-full bg-gray-100">
                                        <div
                                            className="h-3 rounded-full bg-emerald-500"
                                            style={{
                                                width: item.value,
                                            }}
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>

            {/* =====================================================
            ================= POPULAR PACKAGES ====================
            ===================================================== */}

            <div className="grid grid-cols-12 gap-6">
                <div className="col-span-12 lg:col-span-6">
                    <div className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
                        <h2 className="mb-8 text-2xl font-bold">Popular Packages</h2>

                        <div className="space-y-4">
                            {[
                                {
                                    package: "Gold Membership",
                                    sales: "128",
                                },
                                {
                                    package: "Silver Membership",
                                    sales: "102",
                                },
                                {
                                    package: "Premium Membership",
                                    sales: "84",
                                },
                                {
                                    package: "PT Program",
                                    sales: "56",
                                },
                            ].map((item, index) => (
                                <div key={index} className="rounded-2xl border border-gray-100 p-5">
                                    <div className="flex items-center justify-between">
                                        <span>{item.package}</span>

                                        <span className="font-bold">{item.sales}</span>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                {/* UPGRADE ANALYSIS */}

                <div className="col-span-12 lg:col-span-6">
                    <div className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
                        <h2 className="mb-8 text-2xl font-bold">Upgrade Analysis</h2>

                        <div className="space-y-5">
                            {[
                                {
                                    label: "Silver → Gold",
                                    value: "72%",
                                },
                                {
                                    label: "Gold → Premium",
                                    value: "56%",
                                },
                                {
                                    label: "Premium → Elite",
                                    value: "34%",
                                },
                                {
                                    label: "Basic → Gold",
                                    value: "28%",
                                },
                            ].map((item, index) => (
                                <div key={index}>
                                    <div className="mb-3 flex justify-between">
                                        <span>{item.label}</span>

                                        <span>{item.value}</span>
                                    </div>

                                    <div className="h-3 rounded-full bg-gray-100">
                                        <div
                                            className="h-3 rounded-full bg-green-500"
                                            style={{
                                                width: item.value,
                                            }}
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
            {/* =====================================================
            ================= DOWNGRADE ANALYSIS ==================
            ===================================================== */}

            <div className="grid grid-cols-12 gap-6">
                <div className="col-span-12 lg:col-span-6">
                    <div className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
                        <h2 className="mb-8 text-2xl font-bold">Downgrade Analysis</h2>

                        <div className="space-y-5">
                            {[
                                {
                                    label: "Premium → Gold",
                                    value: "42%",
                                },
                                {
                                    label: "Gold → Silver",
                                    value: "31%",
                                },
                                {
                                    label: "Silver → Basic",
                                    value: "24%",
                                },
                                {
                                    label: "Elite → Premium",
                                    value: "16%",
                                },
                            ].map((item, index) => (
                                <div key={index}>
                                    <div className="mb-3 flex items-center justify-between">
                                        <span>{item.label}</span>

                                        <span className="font-semibold">{item.value}</span>
                                    </div>

                                    <div className="h-3 rounded-full bg-gray-100">
                                        <div
                                            className="h-3 rounded-full bg-orange-500"
                                            style={{
                                                width: item.value,
                                            }}
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                {/* RENEWAL ANALYSIS */}

                <div className="col-span-12 lg:col-span-6">
                    <div className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
                        <h2 className="mb-8 text-2xl font-bold">Renewal Analysis</h2>

                        <div className="space-y-4">
                            {[
                                {
                                    month: "January",
                                    value: "78%",
                                },
                                {
                                    month: "February",
                                    value: "82%",
                                },
                                {
                                    month: "March",
                                    value: "87%",
                                },
                                {
                                    month: "April",
                                    value: "91%",
                                },
                            ].map((item, index) => (
                                <div key={index} className="rounded-2xl border border-gray-100 p-5">
                                    <div className="flex items-center justify-between">
                                        <span>{item.month}</span>

                                        <span className="font-bold text-green-600">
                                            {item.value}
                                        </span>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>

            {/* =====================================================
            =================== PACKAGE TRENDS ====================
            ===================================================== */}

            <div className="grid grid-cols-12 gap-6">
                <div className="col-span-12 xl:col-span-7">
                    <div className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
                        <h2 className="mb-8 text-2xl font-bold">Package Trends</h2>

                        <div className="space-y-4">
                            {[
                                {
                                    name: "Gold Membership",
                                    revenue: "₹3.2L",
                                    growth: "+18%",
                                },
                                {
                                    name: "Silver Membership",
                                    revenue: "₹2.4L",
                                    growth: "+12%",
                                },
                                {
                                    name: "Premium Membership",
                                    revenue: "₹1.8L",
                                    growth: "+9%",
                                },
                                {
                                    name: "PT Program",
                                    revenue: "₹1L",
                                    growth: "+22%",
                                },
                            ].map((item, index) => (
                                <div
                                    key={index}
                                    className="flex items-center justify-between rounded-2xl border border-gray-100 p-5"
                                >
                                    <div>
                                        <h3 className="font-semibold">{item.name}</h3>

                                        <p className="text-sm text-gray-500">Revenue Growth</p>
                                    </div>

                                    <div className="text-right">
                                        <h3 className="font-bold">{item.revenue}</h3>

                                        <p className="text-sm text-green-600">{item.growth}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                {/* PROFITABILITY */}

                <div className="col-span-12 xl:col-span-5">
                    <div className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
                        <h2 className="mb-8 text-2xl font-bold">Package Profitability</h2>

                        <div className="space-y-5">
                            {[
                                {
                                    name: "Gold",
                                    profit: "84%",
                                },
                                {
                                    name: "Silver",
                                    profit: "71%",
                                },
                                {
                                    name: "Premium",
                                    profit: "62%",
                                },
                                {
                                    name: "PT",
                                    profit: "48%",
                                },
                            ].map((item, index) => (
                                <div key={index}>
                                    <div className="mb-3 flex justify-between">
                                        <span>{item.name}</span>

                                        <span>{item.profit}</span>
                                    </div>

                                    <div className="h-3 rounded-full bg-gray-100">
                                        <div
                                            className="h-3 rounded-full bg-emerald-500"
                                            style={{
                                                width: item.profit,
                                            }}
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>

            {/* =====================================================
            ====================== AI INSIGHTS ====================
            ===================================================== */}

            <div className="rounded-3xl bg-gradient-to-r from-emerald-600 via-green-600 to-teal-600 p-8 text-white shadow-xl">
                <h2 className="mb-8 text-3xl font-bold">AI Package Insights</h2>

                <div className="grid grid-cols-12 gap-5">
                    <div className="col-span-12 md:col-span-6 xl:col-span-3">
                        <div className="rounded-2xl bg-white/10 p-5">
                            <h3 className="font-semibold">Best Performer</h3>

                            <p className="mt-3 text-xl font-bold">Gold Membership</p>
                        </div>
                    </div>

                    <div className="col-span-12 md:col-span-6 xl:col-span-3">
                        <div className="rounded-2xl bg-white/10 p-5">
                            <h3 className="font-semibold">Fastest Growth</h3>

                            <p className="mt-3 text-xl font-bold">PT Program</p>
                        </div>
                    </div>

                    <div className="col-span-12 md:col-span-6 xl:col-span-3">
                        <div className="rounded-2xl bg-white/10 p-5">
                            <h3 className="font-semibold">Risk Indicator</h3>

                            <p className="mt-3 text-xl font-bold">Renewal Rate Falling</p>
                        </div>
                    </div>

                    <div className="col-span-12 md:col-span-6 xl:col-span-3">
                        <div className="rounded-2xl bg-white/10 p-5">
                            <h3 className="font-semibold">Recommendation</h3>

                            <p className="mt-3 text-xl font-bold">Promote Premium Plans</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}